name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
          
permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Install OpenAPI Generator CLI
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Build SDK
        run: npm run build

      - name: Get current version
        id: current-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump-version
        run: |
          NEW_VERSION=$(npm version ${{ github.event.inputs.version }})
          echo "version=${NEW_VERSION#v}" >> $GITHUB_OUTPUT

      - name: Push changes
        run: git push && git push --tags

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump-version.outputs.version }}
          release_name: Release v${{ steps.bump-version.outputs.version }}
          body: |
            ## Changes
            - Version bump from v${{ steps.current-version.outputs.version }} to v${{ steps.bump-version.outputs.version }}
            - Updated to latest Paystack OpenAPI specification
            - All TypeScript definitions updated
            - Dynamic API client includes all latest endpoints

            ## Installation
            ```bash
            npm install @roarexclamation/paystack-ts-sdk@${{ steps.bump-version.outputs.version }}
            ```
          draft: false
          prerelease: false
